name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20'

    - name: Install dependencies
      run: npm install

    - name: Configure ngrok with auth token
      run: npx ngrok authtoken 2Zpi1Pu3V5vNJqdQEmDZRz4As58_i1wUTV1cqqUoMRUMtZ6z
      
    - name: Start ngrok and expose dev server
      run: |
        npx ngrok http 1337
      continue-on-error: false

    - name: Start dev server
      run: npm run dev 

   
