name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20'

    - name: Install dependencies
      run: npm install

    - name: Start ngrok and expose dev server
      run: |
        npm run dev &
        npx ngrok http 3000 -host-header="localhost:3000"  # Adjust the port if needed
      continue-on-error: true

   
