name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update
        sudo apt-get install ngrok

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20'

    - name: Install dependencies
      run: npm install

    - name: Configure ngrok with auth token
      run: ngrok authtoken 2Zpi1Pu3V5vNJqdQEmDZRz4As58_i1wUTV1cqqUoMRUMtZ6z
      
    - name: Start ngrok tunnel
      run: |
        ngrok http 1337 > ngrok.log 2>&1 &   # Redirect output to a log file
        sleep 5   # Wait for ngrok to start (adjust as needed)
        cat ngrok.log   # Display ngrok log for debugging
        # Check if ngrok is ready by looking for "online" in the log
        grep -q "online" ngrok.log || exit 1
      continue-on-error: false

    - name: Start dev server
      run: npm run dev 

   
